// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/capstone-kelompok-7/backend-disappear/module/entities"
	mock "github.com/stretchr/testify/mock"
)

// ServiceAuthInterface is an autogenerated mock type for the ServiceAuthInterface type
type ServiceAuthInterface struct {
	mock.Mock
}

// Login provides a mock function with given fields: email, password
func (_m *ServiceAuthInterface) Login(email string, password string) (*domain.UserModels, string, error) {
	ret := _m.Called(email, password)

	var r0 *domain.UserModels
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) (*domain.UserModels, string, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *domain.UserModels); ok {
		r0 = rf(email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserModels)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) string); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Register provides a mock function with given fields: newData
func (_m *ServiceAuthInterface) Register(newData *domain.UserModels) (*domain.UserModels, error) {
	ret := _m.Called(newData)

	var r0 *domain.UserModels
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.UserModels) (*domain.UserModels, error)); ok {
		return rf(newData)
	}
	if rf, ok := ret.Get(0).(func(*domain.UserModels) *domain.UserModels); ok {
		r0 = rf(newData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserModels)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.UserModels) error); ok {
		r1 = rf(newData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyEmail provides a mock function with given fields: email, otp
func (_m *ServiceAuthInterface) VerifyEmail(email string, otp string) error {
	ret := _m.Called(email, otp)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewServiceAuthInterface creates a new instance of ServiceAuthInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceAuthInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceAuthInterface {
	mock := &ServiceAuthInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
