// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EmailSenderInterface is an autogenerated mock type for the EmailSenderInterface type
type EmailSenderInterface struct {
	mock.Mock
}

// EmailService provides a mock function with given fields: _a0, otp
func (_m *EmailSenderInterface) EmailService(_a0 string, otp string) error {
	ret := _m.Called(_a0, otp)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEmailSenderInterface creates a new instance of EmailSenderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailSenderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailSenderInterface {
	mock := &EmailSenderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
