// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	entities "github.com/capstone-kelompok-7/backend-disappear/module/entities"
	dto "github.com/capstone-kelompok-7/backend-disappear/module/feature/users/dto"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryUserInterface is an autogenerated mock type for the RepositoryUserInterface type
type RepositoryUserInterface struct {
	mock.Mock
}

// ChangePassword provides a mock function with given fields: userID, newPasswordHash
func (_m *RepositoryUserInterface) ChangePassword(userID uint64, newPasswordHash string) error {
	ret := _m.Called(userID, newPasswordHash)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, string) error); ok {
		r0 = rf(userID, newPasswordHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAccount provides a mock function with given fields: userID
func (_m *RepositoryUserInterface) DeleteAccount(userID uint64) error {
	ret := _m.Called(userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EditProfile provides a mock function with given fields: userID, updatedData
func (_m *RepositoryUserInterface) EditProfile(userID uint64, updatedData dto.EditProfileRequest) (*entities.UserModels, error) {
	ret := _m.Called(userID, updatedData)

	var r0 *entities.UserModels
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, dto.EditProfileRequest) (*entities.UserModels, error)); ok {
		return rf(userID, updatedData)
	}
	if rf, ok := ret.Get(0).(func(uint64, dto.EditProfileRequest) *entities.UserModels); ok {
		r0 = rf(userID, updatedData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.UserModels)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, dto.EditProfileRequest) error); ok {
		r1 = rf(userID, updatedData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: page, perPage
func (_m *RepositoryUserInterface) FindAll(page int, perPage int) ([]*entities.UserModels, error) {
	ret := _m.Called(page, perPage)

	var r0 []*entities.UserModels
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]*entities.UserModels, error)); ok {
		return rf(page, perPage)
	}
	if rf, ok := ret.Get(0).(func(int, int) []*entities.UserModels); ok {
		r0 = rf(page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.UserModels)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByName provides a mock function with given fields: page, perPage, name
func (_m *RepositoryUserInterface) FindByName(page int, perPage int, name string) ([]*entities.UserModels, error) {
	ret := _m.Called(page, perPage, name)

	var r0 []*entities.UserModels
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]*entities.UserModels, error)); ok {
		return rf(page, perPage, name)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []*entities.UserModels); ok {
		r0 = rf(page, perPage, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.UserModels)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) error); ok {
		r1 = rf(page, perPage, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllUsersBySearchAndFilter provides a mock function with given fields: page, perPage, search, levelFilter
func (_m *RepositoryUserInterface) GetAllUsersBySearchAndFilter(page int, perPage int, search string, levelFilter string) ([]*entities.UserModels, int64, error) {
	ret := _m.Called(page, perPage, search, levelFilter)

	var r0 []*entities.UserModels
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, string, string) ([]*entities.UserModels, int64, error)); ok {
		return rf(page, perPage, search, levelFilter)
	}
	if rf, ok := ret.Get(0).(func(int, int, string, string) []*entities.UserModels); ok {
		r0 = rf(page, perPage, search, levelFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.UserModels)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string, string) int64); ok {
		r1 = rf(page, perPage, search, levelFilter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, string, string) error); ok {
		r2 = rf(page, perPage, search, levelFilter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetFilterLevel provides a mock function with given fields: page, perPage, level
func (_m *RepositoryUserInterface) GetFilterLevel(page int, perPage int, level string) ([]*entities.UserModels, int64, error) {
	ret := _m.Called(page, perPage, level)

	var r0 []*entities.UserModels
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]*entities.UserModels, int64, error)); ok {
		return rf(page, perPage, level)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []*entities.UserModels); ok {
		r0 = rf(page, perPage, level)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.UserModels)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) int64); ok {
		r1 = rf(page, perPage, level)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, string) error); ok {
		r2 = rf(page, perPage, level)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetLeaderboardByExp provides a mock function with given fields: limit
func (_m *RepositoryUserInterface) GetLeaderboardByExp(limit int) ([]*entities.UserModels, error) {
	ret := _m.Called(limit)

	var r0 []*entities.UserModels
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]*entities.UserModels, error)); ok {
		return rf(limit)
	}
	if rf, ok := ret.Get(0).(func(int) []*entities.UserModels); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.UserModels)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalUserCount provides a mock function with given fields:
func (_m *RepositoryUserInterface) GetTotalUserCount() (int64, error) {
	ret := _m.Called()

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalUserCountByName provides a mock function with given fields: name
func (_m *RepositoryUserInterface) GetTotalUserCountByName(name string) (int64, error) {
	ret := _m.Called(name)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserChallengeActivity provides a mock function with given fields: userID
func (_m *RepositoryUserInterface) GetUserChallengeActivity(userID uint64) (int, int, int, error) {
	ret := _m.Called(userID)

	var r0 int
	var r1 int
	var r2 int
	var r3 error
	if rf, ok := ret.Get(0).(func(uint64) (int, int, int, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint64) int); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(uint64) int); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(uint64) int); ok {
		r2 = rf(userID)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(uint64) error); ok {
		r3 = rf(userID)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetUserLevel provides a mock function with given fields: userID
func (_m *RepositoryUserInterface) GetUserLevel(userID uint64) (string, error) {
	ret := _m.Called(userID)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint64) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserTransactionActivity provides a mock function with given fields: userID
func (_m *RepositoryUserInterface) GetUserTransactionActivity(userID uint64) (int, int, int, error) {
	ret := _m.Called(userID)

	var r0 int
	var r1 int
	var r2 int
	var r3 error
	if rf, ok := ret.Get(0).(func(uint64) (int, int, int, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint64) int); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(uint64) int); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(uint64) int); ok {
		r2 = rf(userID)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(uint64) error); ok {
		r3 = rf(userID)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetUsersByEmail provides a mock function with given fields: email
func (_m *RepositoryUserInterface) GetUsersByEmail(email string) (*entities.UserModels, error) {
	ret := _m.Called(email)

	var r0 *entities.UserModels
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.UserModels, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.UserModels); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.UserModels)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersById provides a mock function with given fields: userId
func (_m *RepositoryUserInterface) GetUsersById(userId uint64) (*entities.UserModels, error) {
	ret := _m.Called(userId)

	var r0 *entities.UserModels
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*entities.UserModels, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(uint64) *entities.UserModels); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.UserModels)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersPassword provides a mock function with given fields: userID
func (_m *RepositoryUserInterface) GetUsersPassword(userID uint64) (string, error) {
	ret := _m.Called(userID)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint64) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserChallengeFollow provides a mock function with given fields: userID, totalChallenge
func (_m *RepositoryUserInterface) UpdateUserChallengeFollow(userID uint64, totalChallenge uint64) (*entities.UserModels, error) {
	ret := _m.Called(userID, totalChallenge)

	var r0 *entities.UserModels
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, uint64) (*entities.UserModels, error)); ok {
		return rf(userID, totalChallenge)
	}
	if rf, ok := ret.Get(0).(func(uint64, uint64) *entities.UserModels); ok {
		r0 = rf(userID, totalChallenge)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.UserModels)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, uint64) error); ok {
		r1 = rf(userID, totalChallenge)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserContribution provides a mock function with given fields: userID, gramPlastic
func (_m *RepositoryUserInterface) UpdateUserContribution(userID uint64, gramPlastic uint64) (*entities.UserModels, error) {
	ret := _m.Called(userID, gramPlastic)

	var r0 *entities.UserModels
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, uint64) (*entities.UserModels, error)); ok {
		return rf(userID, gramPlastic)
	}
	if rf, ok := ret.Get(0).(func(uint64, uint64) *entities.UserModels); ok {
		r0 = rf(userID, gramPlastic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.UserModels)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, uint64) error); ok {
		r1 = rf(userID, gramPlastic)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserExp provides a mock function with given fields: userID, exp
func (_m *RepositoryUserInterface) UpdateUserExp(userID uint64, exp uint64) (*entities.UserModels, error) {
	ret := _m.Called(userID, exp)

	var r0 *entities.UserModels
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, uint64) (*entities.UserModels, error)); ok {
		return rf(userID, exp)
	}
	if rf, ok := ret.Get(0).(func(uint64, uint64) *entities.UserModels); ok {
		r0 = rf(userID, exp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.UserModels)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, uint64) error); ok {
		r1 = rf(userID, exp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserLevel provides a mock function with given fields: userID, level
func (_m *RepositoryUserInterface) UpdateUserLevel(userID uint64, level string) error {
	ret := _m.Called(userID, level)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, string) error); ok {
		r0 = rf(userID, level)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepositoryUserInterface creates a new instance of RepositoryUserInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryUserInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryUserInterface {
	mock := &RepositoryUserInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
