// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	entities "github.com/capstone-kelompok-7/backend-disappear/module/entities"

	mock "github.com/stretchr/testify/mock"

	sendnotif "github.com/capstone-kelompok-7/backend-disappear/utils/sendnotif"
)

// RepositoryFcmInterface is an autogenerated mock type for the RepositoryFcmInterface type
type RepositoryFcmInterface struct {
	mock.Mock
}

// CreateFcm provides a mock function with given fields: _a0
func (_m *RepositoryFcmInterface) CreateFcm(_a0 *entities.FcmModels) (*entities.FcmModels, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateFcm")
	}

	var r0 *entities.FcmModels
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.FcmModels) (*entities.FcmModels, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*entities.FcmModels) *entities.FcmModels); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.FcmModels)
		}
	}

	if rf, ok := ret.Get(1).(func(*entities.FcmModels) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteFcmById provides a mock function with given fields: id
func (_m *RepositoryFcmInterface) DeleteFcmById(id uint64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFcmById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFcmById provides a mock function with given fields: id
func (_m *RepositoryFcmInterface) GetFcmById(id uint64) (*entities.FcmModels, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetFcmById")
	}

	var r0 *entities.FcmModels
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*entities.FcmModels, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint64) *entities.FcmModels); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.FcmModels)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFcmByIdUser provides a mock function with given fields: id
func (_m *RepositoryFcmInterface) GetFcmByIdUser(id uint64) ([]*entities.FcmModels, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetFcmByIdUser")
	}

	var r0 []*entities.FcmModels
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) ([]*entities.FcmModels, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint64) []*entities.FcmModels); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.FcmModels)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendMessageNotification provides a mock function with given fields: request
func (_m *RepositoryFcmInterface) SendMessageNotification(request sendnotif.SendNotificationRequest) (string, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageNotification")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(sendnotif.SendNotificationRequest) (string, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(sendnotif.SendNotificationRequest) string); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(sendnotif.SendNotificationRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepositoryFcmInterface creates a new instance of RepositoryFcmInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryFcmInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryFcmInterface {
	mock := &RepositoryFcmInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
