// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// HandlerHomepageInterface is an autogenerated mock type for the HandlerHomepageInterface type
type HandlerHomepageInterface struct {
	mock.Mock
}

// GetBlogPost provides a mock function with given fields:
func (_m *HandlerHomepageInterface) GetBlogPost() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// GetHomepageContent provides a mock function with given fields:
func (_m *HandlerHomepageInterface) GetHomepageContent() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// NewHandlerHomepageInterface creates a new instance of HandlerHomepageInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandlerHomepageInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *HandlerHomepageInterface {
	mock := &HandlerHomepageInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
