// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import (
	entities "github.com/capstone-kelompok-7/backend-disappear/module/entities"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryHomepageInterface is an autogenerated mock type for the RepositoryHomepageInterface type
type RepositoryHomepageInterface struct {
	mock.Mock
}

// GetBestSellingProducts provides a mock function with given fields: limit
func (_m *RepositoryHomepageInterface) GetBestSellingProducts(limit int) ([]*entities.ProductModels, error) {
	ret := _m.Called(limit)

	var r0 []*entities.ProductModels
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]*entities.ProductModels, error)); ok {
		return rf(limit)
	}
	if rf, ok := ret.Get(0).(func(int) []*entities.ProductModels); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.ProductModels)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFiveCarousel provides a mock function with given fields:
func (_m *RepositoryHomepageInterface) GetFiveCarousel() ([]*entities.CarouselModels, error) {
	ret := _m.Called()

	var r0 []*entities.CarouselModels
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*entities.CarouselModels, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*entities.CarouselModels); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.CarouselModels)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFiveCategories provides a mock function with given fields:
func (_m *RepositoryHomepageInterface) GetFiveCategories() ([]*entities.CategoryModels, error) {
	ret := _m.Called()

	var r0 []*entities.CategoryModels
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*entities.CategoryModels, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*entities.CategoryModels); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.CategoryModels)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFiveChallenge provides a mock function with given fields:
func (_m *RepositoryHomepageInterface) GetFiveChallenge() ([]*entities.ChallengeModels, error) {
	ret := _m.Called()

	var r0 []*entities.ChallengeModels
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*entities.ChallengeModels, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*entities.ChallengeModels); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.ChallengeModels)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetThreeArticle provides a mock function with given fields:
func (_m *RepositoryHomepageInterface) GetThreeArticle() ([]*entities.ArticleModels, error) {
	ret := _m.Called()

	var r0 []*entities.ArticleModels
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*entities.ArticleModels, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*entities.ArticleModels); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.ArticleModels)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepositoryHomepageInterface creates a new instance of RepositoryHomepageInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryHomepageInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryHomepageInterface {
	mock := &RepositoryHomepageInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
