// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import (
	entities "github.com/capstone-kelompok-7/backend-disappear/module/entities"
	dto "github.com/capstone-kelompok-7/backend-disappear/module/feature/address/dto"

	mock "github.com/stretchr/testify/mock"
)

// ServiceAddressInterface is an autogenerated mock type for the ServiceAddressInterface type
type ServiceAddressInterface struct {
	mock.Mock
}

// CalculatePaginationValues provides a mock function with given fields: page, totalItems, perPage
func (_m *ServiceAddressInterface) CalculatePaginationValues(page int, totalItems int, perPage int) (int, int) {
	ret := _m.Called(page, totalItems, perPage)

	var r0 int
	var r1 int
	if rf, ok := ret.Get(0).(func(int, int, int) (int, int)); ok {
		return rf(page, totalItems, perPage)
	}
	if rf, ok := ret.Get(0).(func(int, int, int) int); ok {
		r0 = rf(page, totalItems, perPage)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int, int, int) int); ok {
		r1 = rf(page, totalItems, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}

// CreateAddress provides a mock function with given fields: newData
func (_m *ServiceAddressInterface) CreateAddress(newData *entities.AddressModels) (*entities.AddressModels, error) {
	ret := _m.Called(newData)

	var r0 *entities.AddressModels
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.AddressModels) (*entities.AddressModels, error)); ok {
		return rf(newData)
	}
	if rf, ok := ret.Get(0).(func(*entities.AddressModels) *entities.AddressModels); ok {
		r0 = rf(newData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AddressModels)
		}
	}

	if rf, ok := ret.Get(1).(func(*entities.AddressModels) error); ok {
		r1 = rf(newData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAddress provides a mock function with given fields: addressID, userID
func (_m *ServiceAddressInterface) DeleteAddress(addressID uint64, userID uint64) error {
	ret := _m.Called(addressID, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, uint64) error); ok {
		r0 = rf(addressID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAddressByID provides a mock function with given fields: addressID
func (_m *ServiceAddressInterface) GetAddressByID(addressID uint64) (*entities.AddressModels, error) {
	ret := _m.Called(addressID)

	var r0 *entities.AddressModels
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*entities.AddressModels, error)); ok {
		return rf(addressID)
	}
	if rf, ok := ret.Get(0).(func(uint64) *entities.AddressModels); ok {
		r0 = rf(addressID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.AddressModels)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(addressID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: userID, page, perPage
func (_m *ServiceAddressInterface) GetAll(userID uint64, page int, perPage int) ([]*entities.AddressModels, int64, error) {
	ret := _m.Called(userID, page, perPage)

	var r0 []*entities.AddressModels
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(uint64, int, int) ([]*entities.AddressModels, int64, error)); ok {
		return rf(userID, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(uint64, int, int) []*entities.AddressModels); ok {
		r0 = rf(userID, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.AddressModels)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64, int, int) int64); ok {
		r1 = rf(userID, page, perPage)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(uint64, int, int) error); ok {
		r2 = rf(userID, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetNextPage provides a mock function with given fields: currentPage, totalPages
func (_m *ServiceAddressInterface) GetNextPage(currentPage int, totalPages int) int {
	ret := _m.Called(currentPage, totalPages)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, int) int); ok {
		r0 = rf(currentPage, totalPages)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetPrevPage provides a mock function with given fields: currentPage
func (_m *ServiceAddressInterface) GetPrevPage(currentPage int) int {
	ret := _m.Called(currentPage)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(currentPage)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// UpdateAddress provides a mock function with given fields: userID, addressID, updatedAddress
func (_m *ServiceAddressInterface) UpdateAddress(userID uint64, addressID uint64, updatedAddress *dto.UpdateAddressRequest) error {
	ret := _m.Called(userID, addressID, updatedAddress)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, uint64, *dto.UpdateAddressRequest) error); ok {
		r0 = rf(userID, addressID, updatedAddress)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewServiceAddressInterface creates a new instance of ServiceAddressInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceAddressInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceAddressInterface {
	mock := &ServiceAddressInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
